server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.telemetry: INFO
    org.springframework: INFO